container:
  image: ubuntu:latest
  cpu: 8
  memory: 16G
  
task:
  timeout_in: 90m
  enviroment:
    TOKEN: ENCRYPTED[fb3817d3349eab96ea55ffde49ec4c79f421b04b10de4cf02973ea1d1fd080efc59a85b0ad6f059eb9fe45c3e281ed24]
  script:
   - dir
